### PR TITLE
Build for cjs, esm, web script (iife) and web module

### LINKED ISSUE #73: ES6 target / ESM distribution
Hi, would it be possible to release a version of the library compiled to ES6, so using and exporting native modules?
Recent versions of Angular complain about non-ESM dependencies (i.e. AMD or CommonJS).

### PR DESCRIPTION
**Pull request by RebeccaStevens**
fix #73

Adds rollup and tsconfig files.

### CODE REVIEW

**Comment by vitaly-t** [comment]
I'm currently looking into why running `npm test` produces:

```
> TS_NODE_PROJECT=tsconfig.test.json nyc mocha -r ts-node/register test/**/*.spec.ts

'TS_NODE_PROJECT' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by RebeccaStevens** [comment]
Are you running on windows? `TS_NODE_PROJECT=tsconfig.test.json` is supposed to set an environment variable. We'll need to use something like [cross-env](https://www.npmjs.com/package/cross-env) to make it work on windows.

**Comment by vitaly-t** [comment]
Yes, I'm using Windows 10 :|

**Comment by RebeccaStevens** [comment]
I use WSL for all my development these days. Makes things way easier in my opinion.
Anyway, I just added cross-env so it should work for you now.

**Comment by vitaly-t** [comment]
The tests can run now, but quote oddly, every occurrence of conditional chaining in the code, like `var?.property` falls out of the code coverage, even though tests definitely at 100%, but branches come up at 97% now.

**Comment by RebeccaStevens** [comment]
I'll look into it

**Comment by vitaly-t** [comment]
Also, there's some circular dependency suddenly somehow, when running `npm run build`:

image

**Comment by RebeccaStevens** [comment]
That would have already been in your codebase. Rollup just found them and is reporting on them.

**Comment by vitaly-t** [comment]
Actually, the latter is on me, it was there before, I think, just not detected, I will fix this :)

**Comment by vitaly-t** [comment]
Also, to clarify, all that content I have within the [./web](https://github.com/vitaly-t/iter-ops/tree/main/web) folder - is it of no use anymore?

**Comment by RebeccaStevens** [comment]
I think with regard to branches' coverage dropping down to 97%, this is the correct behavior. You're only testing the happy path when it comes to optional chaining. It could be that the optional chains aren't even needed.
I'm not sure why you were getting 100% before; it probably had something to do with not have a tsconfig file.

**Comment by RebeccaStevens** [comment]
I haven't remove the need for the `web` folder but this could easily be done.

**Comment by vitaly-t** [comment]
> I haven't remove the need for the `web` folder

I'm sorry, I'm not sure what you mean by remove the need for it :) Could you, please clarify?

In the meantime, I have published a beta from this branch, I tried it with an Angular project - all seems fine 👍

**Comment by vitaly-t** [comment]
Please advise what should I do with the `./web` folder and the package it is creating... 🙏 Or are you making more changes to this PR?

**Comment by RebeccaStevens** [comment]
I've remove the `web` folder and made it so rollup builds a web version. You can deprecate the web package.

**Comment by vitaly-t** [comment]
I've pulled the latest code, but I see the `web` folder still there, and `npm run build` seems to be producing the same as before.

I must be missing something?

**Comment by vitaly-t** [comment]
That last commit seems to be going into a separate branch. Any chance I'm missing the latest code here because of that?

**Comment by RebeccaStevens** [comment]
Looking at the changes here on GitHub, everything seems to be fine. The web folder might still exists but it should be empty. The build script should output 2 files into the dist folder and 6 files into dist/web.

**Comment by vitaly-t** [comment]
Looks like something got messed up locally. Anyhow, I have merged the branch, and it all seems very good, thank you!!!

I believe I can still use that Web folder though, to mention the min file and all :)

One question - I noticed the MIN file is generated with MS license. Do you know how to make include my own license like it did before?

**Comment by RebeccaStevens** [comment]
Both license should be included.

image

**Comment by vitaly-t** [comment]
Yep, didn't see it the first time. I still would throw the MS out, from what I see in othjer packages, hardly anyone includes more than one license.

I have added that `sideEffects` flag, cheers! And solved the circular dependencies :) It looks almost ready :)

**Comment by RebeccaStevens** [comment]
If you want to change what comments are kept and what ones are thrown away, look into [terser's comment config](https://github.com/terser/terser#format-options) ([configured here](https://github.com/vitaly-t/iter-ops/blob/main/rollup.config.ts#L124)).
You could set it to function for full control e.g.

```ts
comments: function (node, comment) {
    const text = comment.value;
    const type = comment.type;

    // multiline comment
    if (type == "comment2" && some_other_test) {
        // keep comment
        return true;
    }

    // discard comment
    return false;
}
```

**Comment by vitaly-t** [comment]
@RebeccaStevens I seem to have a problem with regular NodeJS apps in TypeScript. The library distribution stopped including `.d.ts` - declaration files, so Typescript can no longer resolve those.

**Comment by RebeccaStevens** [comment]
@vitaly-t Fixed in #80

**Comment by vitaly-t** [comment]
@RebeccaStevens I have tested it, and left my comment there ;)

**Comment by vitaly-t** [comment]
@RebeccaStevens That plug-in had a few distributions screwed up at this point, very annoying - see [the issue I opened](https://github.com/Swatinem/rollup-plugin-dts/issues/190).

**Comment by RebeccaStevens** [comment]
That is a weird issue you're having. I've never experienced anything like that before with it. Though I pretty much only ever run these sort of build tools in CI environments, so I probably never would have noticed this kind of thing. I'm not even really sure where I'd start to look for the cause of such an issue.

**Comment by vitaly-t** [comment]
Yep, so I just published 1.6.0 - another broken version because that plugin again generated some obsolete declarations. So I had to remove the entire repo and pull it again, to make it start generating the latest declarations again. It's a very odd issue.

**Pull request merged**
