### PR TITLE
add spellchecking

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Comment by vitaly-t** [comment]
Conflicts came up from the previous merges ;)

**Comment by RebeccaStevens** [comment]
fixed

**Comment by vitaly-t** [comment]
@RebeccaStevens Thank you!!! Great job! :smile:

If you are done, let me know, please, I'd like to release a build, after so many changes :wink:

**Comment by RebeccaStevens** [comment]
One last thing coming up.

**Pull request merged**
