### PR TITLE
feat: new operation: join

### PR DESCRIPTION
**Pull request by RebeccaStevens**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join

### CODE REVIEW

**Comment by vitaly-t** [comment]
This library doesn't feature any data-type-specific operator, I wasn't planning on adding one...

This operator, if it has any value, is only with the strings. It has no semantic value for objects, or even simple numbers.

In fact, if one wants to join strings, a simple `aggregate(a => a.join())` can do that.

I really wish you were to open a [discussion](https://github.com/vitaly-t/iter-ops/discussions) on something like this first, because I see that you've already put in a lot of work on this, before it was even discussed.

**Comment by vitaly-t** [comment]
P.S. This is probably the most I can respond to during new year holidays. Back some time next week.

**Comment by RebeccaStevens** [comment]
That's all good. I'm just working on this as I don't really have anything else to do right now and I enjoy it.

My reasoning for adding `join` was simply just because it exists on `Array`. When an array of non-strings is joint, each value is simple converted to a sting (e.g. via `.toString` for objects) so that's what I made this do.

**Comment by vitaly-t** [comment]
@RebeccaStevens I am voting to close this, because the end result is easily achievable via operator [aggregate](https://vitaly-t.github.io/iter-ops/functions/aggregate.html):

```ts
aggregate(a => a.join(separator))
```

And if you want a dedicated operator to do the same, just declare one:

```ts
function join(separator?: string) {
    return aggregate(a => a.join(separator));
}
```

**Comment by vitaly-t** [comment]
@RebeccaStevens 

I am re-opening it now that I have a little time to look closer into it...

I understand your reasoning for opening this PR in the first place, and I can add one more - to be able to generate the final string as we iterate through is better because we can interrupt the iterable at any point.

At first glance, I notice the issue with the defaults. The default is `','` and not `''`, which is incorrect in your code + inline code example ;)

In case you want to revive this :wink:

**Comment by vitaly-t** [comment]
Ok, after more looking into it, I retract my sentiment about iteration:

>  to be able to generate the final string as we iterate through is better because we can interrupt the iterable at any point.

Since it is required to output just one value, we no longer have any value added from the iteration itself. That probably was my argument back then for not having this this.

**Comment by vitaly-t** [comment]
Ok, after much consideration, I decided to get away with an addition of [join] paragraph within [Recipes], and close this PR once again.

@RebeccaStevens  Sorry for the turbulence.

[join]:https://github.com/vitaly-t/iter-ops/wiki/Recipes#join
[Recipes]:https://github.com/vitaly-t/iter-ops/wiki/Recipes

**Pull request closed without merging**
