### PR TITLE
Wait cache

### PR DESCRIPTION
**Pull request by vitaly-t**

### CODE REVIEW

**Comment by bergus** [comment]
This seems really sketchy. From looking at its usage, it's unclear whether `i` is expected to be an `Iterator<Promise<T>>` or an `AsyncIterator<T>`, i.e. whether `i.next()` returns a `Promise<IteratorResult<T>>` or an `IteratorResult<Promise<T>>`.

Or really, `waitCache` seems to only work as documented (i.e. waiting for multiple things concurrently) when you get back a `Promise<IteratorResult<Promise<T>>>`, which should not happen with normal `AsyncIterator` implementations.

**Comment by vitaly-t** [comment]
@bergus I've struggled with the performance-related issues, but I got it all sorted out in the end:

* [Here's the final code](https://github.com/vitaly-t/iter-ops/blob/main/src/ops/async/wait-race.ts)
* [Here's the original discussion here](https://github.com/vitaly-t/iter-ops/discussions/179)
* [Here's generated documentation](https://vitaly-t.github.io/iter-ops/functions/waitRace.html)

**Comment by bergus** [comment]
I did look at the final code, but [it doesn't seem to be so different](https://github.com/vitaly-t/iter-ops/compare/wait-cache...bcb2ef9) so I figured this PR would be the appropriate place to comment (better than the locked StackOverflow question).
I'm not familiar with your library (don't know the details of `map` and `pipeAsync`) so I might be missing something, but how does this actually run multiple things concurrently if consumed by a sequential `for await` loop? Wouldn't you have to call `next()` multiple times in quick succession even before the previous call (promise) completed?

**Comment by vitaly-t** [comment]
A sequential `for await` accounts just for the sequence itself, i.e. `Promise<Promise<IteratorResult<T>>>`. When you re-map the actual values into promises, using `map`, for example, then you'd need:

```ts
for await (const a of i) {
    await a; // because values themselves are promises
}
```

that's why we have `wait` that can resolve those automatically:

```ts
const i = pipeAsync([1, 2, 3], map(a => Promise.resolve(a)), wait());
```

And so `waitRace` caches those up, and then runs `Promise.race` on those values.

**Comment by bergus** [comment]
Ah, so it really needs to be an `AsyncIterable<Promise<T>>` for the concurrency to take place, `AsyncIterable<T>` is not enough.
I did not see `wait`, I had expected `map` to implicitly take care of that - but I guess then it would at least be `mapAsync` or something.

**Comment by vitaly-t** [comment]
> I had expected `map` to implicitly take care of that

Our re-mapping operators, like `map` and `aggregate` do not resolve promises, because there are a number of ways they can be resolved, and it would take away the freedom of choosing how they should be resolved.

With our approach you can append `wait` for one-by-one resolution, you can aggregate into an array and then do `Promise.all`, or you can do now `waitRace` to cache them up and race-resolve.

**Comment by vitaly-t** [comment]
@bergus I have updated [map documentation](https://vitaly-t.github.io/iter-ops/functions/map.html) to explain why it does not resolve any promises.

**Pull request merged**
