### PR TITLE
ci: set up CI

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Comment by vitaly-t** [comment]
What are those check warnings that follow the changes?

**Comment by RebeccaStevens** [comment]
This PR adds those checks so that any new PR will run the tests (as well as linting and spellchecking) automatically. This allows for (hopefully) all unexpected breakages to be caught early before merging.

Yes, this uses GitHub Actions.

**Comment by vitaly-t** [comment]
Also, just tried to run `npm run lint`, got this:

image

😅

**Comment by RebeccaStevens** [comment]
ahh, it's probably complaining about line endings.

**Comment by vitaly-t** [comment]
Merged, but we need to fix those linting issues ;)

**Pull request merged**
