### PR TITLE
refactor: rename types starting with "Any"

### PR DESCRIPTION
**Pull request by RebeccaStevens**
BREAKING CHANGE: Types starting with "Any" have been renamed

This is an opinionated PR so feel free to reject it. I can also make adjustments to prevent there being a breaking change if you don't want to introduce one.

My reasoning for the changes being:

For `Any` and `AnySync`:

- the name doesn't really explain what it is. Any what?

For `AnyIterable`, `AnyIterator` and `AnyIterableIterator`

- "unknown" seems more consistent with TypeScript's naming convention
  - As we don't know anything about what type of type it is (i.e. it's like `unknown` rather than `any`)

### CODE REVIEW

**Comment by vitaly-t** [comment]
I'm thinking if `SyncValue` is better than `ValueSync`, from English perspective.

**Comment by RebeccaStevens** [comment]
From an English point of view, yes `SyncValue` would be best.

My main reasoning for having it as `ValueSync` is because it gives them an intrinsic link between it and `Value`.

For example:\
With `ValueSync` and `ValueAsync`, the name says "This is a value, the type of value is sync/async".
While with `SyncValue` and `AsyncValue`, the name says "This is sync/async and it is a value".

This does then contradict `UnknownIterable`, so that should probably be `IterableUnknown` by the same reasoning.

I'm happy to use either naming conversion so just let me know what one and I'll make the change. :)

**Comment by vitaly-t** [comment]
I think that sticking with plain English is better ;) So `SyncValue` or `AsyncValue` is better then ;)

**Comment by RebeccaStevens** [comment]
Change made

**Comment by vitaly-t** [comment]
Thanks! Merged ;)

**Pull request merged**
