### PR TITLE
feat: add async callback support to operator `reduce`

### LINKED ISSUE #181: Add async callback support to operator "reduce"
Most of operators that provide a callback support async result from it, where it may be useful.

There maybe cases when `reduce` could benefit from handling async callbacks also.

### PR DESCRIPTION
**Pull request by RebeccaStevens**
fix #181

### CODE REVIEW

**Comment by vitaly-t** [comment]
In #181, I mentioned that we might allow the initial value to be a promise. And in the one-line solution that I gave, it would handle a Promise as the initial value.

In your solution, you do not allow it. Could you, please share your thoughts on why not?

**Review by vitaly-t — COMMENTED** [review]
Needs some response in relation to the initial value, not supporting Promise.

**Review by vitaly-t — APPROVED** [review]
LGTM

**Comment by RebeccaStevens** [comment]
Adding support for a promise as the initial value was a little bit tricker but I've added it now.
The one-line solution you gave was close to what was needed but didn't quite work.
(The first argument passed to the callback, should be the awaited value, not the promise itself)

**Comment by vitaly-t** [comment]
[I have refactored out an extraneous promise there](https://github.com/vitaly-t/iter-ops/commit/50269b8013dbc221f4b89660111346222a53ef48). I hope you don't mind :smile:

**Pull request merged**
