### PR TITLE
feat: decouple sync and async operators

### PR DESCRIPTION
**Pull request by RebeccaStevens**
BREAKING CHANGE: Some minor changes to the public API

### Overview

This PR decouples sync and async operation from each other, but still allows for a common operation to be used in both the sync and async pipelines.

Previously, each operator had a sync and async function. E.g.

```ts
export function aggregate<T, R>(...): Operation<T, R>;
function aggregateSync<T, R>(...): Iterable<R>;
function aggregateAsync<T, R>(...): AsyncIterable<R>;
```

But now, each of those function is a full featured operation.

```ts
export function aggregate<T, R>(...): DuelOperation<T, R>
export function aggregateSync<T, R>(...): SyncOperation<T, R>;
export function aggregateAsync<T, R>(...): AsyncOperation<T, R>;
```

These new operations are not just exposed like the original ones in order to prevent clutter. Instead they are scoped respectively in the sync and async namespaces. These can be access with

```ts
import { sync, async } from "iter-ops";
```

Or when using node 16 or newer:

```ts
import { * as sync } from "iter-ops/sync";
import { * as async } from "iter-ops/async";
```

##### Bundles Made by Users (Better performance?)

Currently with the way things are set up, if you use the sync version of an operator, you cannot decouple the async version from it. This is because the function returned by the `createOperator` function needs to keep a reference to both the sync and async version. This in turn means that users have to ship both and not just the one they are using (i.e. they have to ship deadcode).

##### Bundles Made by Us

We are now able to provide a sync-only and an async-only bundle as well as the full bundle, giving users more choice in how they wish to consume this library.

#### Fixed Type Issues

Although this PR doesn't resolve the type issues for the original operations (now called dual operations), the sync-only and async-only operations do not have these issues. The reason for the issues with original operations comes when trying to merge the sync and async ones into as single operation.

### CODE REVIEW

**Comment by vitaly-t** [comment]
182 changes! HFS! 😆 And I thought I lost you 😄 

Do you think this is going to break operators in [iter-ops-extra](https://github.com/vitaly-t/iter-ops-extras)?

Anyhow, I was about to fall asleep, will be needing a fresh head to look through something so big...

**Comment by RebeccaStevens** [comment]
I'll quickly resolve the conflict.

The vast majority of the changes come from the fact that each operation is now split up into 3 files.

The same restructuring will probably need to be made to `iter-ops-extra` to keep it compatible.

**Comment by RebeccaStevens** [comment]
I've also made a minor change to the way the `reduce` operator works to make it better at inferring types.

**Comment by vitaly-t** [comment]
This is a very big change... which I want to understand well before merging.

I have published `2.7.0-beta.0` right from the PR branch for now, so I can test it out properly. In particular, the changes in use of `pipe` vs old `pipeAsync` and `pipeSync` are interesting...

You know that `pipeAsync` is mentioned in a few inline code examples in jsDoc comments - those will need to be updated (I will do so), plus a few places in the WiKi.

I will resume this review tomorrow ;)

**Comment by vitaly-t** [comment]
Merged. I had a quick look through the code, looks like a lot of tests are based on `pipeAsync`, we need to refactor it out ;) We do not want deprecated functions used in the code or documentation anywhere ;)

**Comment by vitaly-t** [comment]
I must be missing something basic here, but I cannot get any kind of code to work anymore, they all come up in error. Could you, please provide a usable example for any-pipe, async-pipe and sync-pipe?

**Comment by vitaly-t** [comment]
Please follow this up in #203.

**Pull request merged**
