### PR TITLE
fix: restore types to build

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Comment by vitaly-t** [comment]
Cheers! I'm gonna get this one, publish it as a beta, and do full client test :smile:

**Comment by vitaly-t** [comment]
There's something a little odd going for JavaScript NodeJS clients...

So I've published this PR as `1.5.1-beta.0`, and when I try to use it from a TypeScript NodeJS client, and navigate to any declaration, it looks fine, like this:

image

But, when I'm trying to do the same from a JavaScript NodeJS client, then suddenly the JS fails to see all the standard types...

image

Before all the changes, JavaScript and TypeScript clients could see all the declarations the same, but not anymore.

Any idea what might be causing this?

**Comment by vitaly-t** [comment]
At first, I thought that adding `@types/node` dependency might help, but no, it didn't 😮

**Comment by vitaly-t** [comment]
Other than that, the code works fine under JavaScript, but my IDE shows all standard declarations as unresolved.

Here's a simple test app:

```js
const {delay, pipe, toAsync} = require('iter-ops');

const i = pipe(toAsync([1, 2, 3, 4, 5]), delay(300));

(async function test() {
    for await (const a of i) {
        console.log(a);
    }
})();
```

**Comment by vitaly-t** [comment]
P.S. I don't mean this being a minor inconvenience, because the code itself is even shown as incorrect, even though it runs:

image

And it is not something IDE-specific. I use WebStorm, and I have purged all the previous installations and the IDE cache completely, so it is the environment.

**Comment by RebeccaStevens** [comment]
Weird. I tried to recreate the issue but was unable to.

**Comment by RebeccaStevens** [comment]
I think the cause of the problem is that `AsyncIterable` and the like are defined in `typescript/lib/lib.es2018.asynciterable.d.ts`; so in TypeScript itself. Without typescript present in your IDE it doesn't know that they are. I'm not having this issue in VSCode.

**Comment by vitaly-t** [comment]
I tried, and installed VSCode too. But that IDE doesn't do any kind of parsing for a JavaScript code, it seems, so I'm not sure.

b.t.w., I've published that addition of `types` as `1.5.1-beta.1`, but it didn't make any difference.

**Comment by vitaly-t** [comment]
Something worth mentioning,...I've just renamed my JS file into MJS, changed `require` to `import` there, and it shows all declarations perfectly after that, just not for JavaScript files. It is odd.

**Comment by vitaly-t** [comment]
I'm merging it in the meantime. Maybe something will come up later what's going on there...

**Pull request merged**
