### PR TITLE
chore: switch to yarn 3

### PR DESCRIPTION
**Pull request by RebeccaStevens**

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
Don't merge yet

**Comment by RebeccaStevens** [comment]
I accidently add something that was part of something else to the commit. It's all good, now. Feel free to merge.

**Comment by vitaly-t** [comment]
@RebeccaStevens Our `npm run format` reformats `yarn.lock` file. I haven't checked it in  - left for you to check if this is needed, or to be added into ignore list?

**Comment by RebeccaStevens** [comment]
Looking into it

**Comment by RebeccaStevens** [comment]
@vitaly-t The formatting script should only effect ts files.

Discard any changes you have to that file and try running `yarn format` instead.
Also, which version of yarn do you have installed (run `yarn -v`). If it's v1, run `corepack enable` and then seen if it's now v3.

**Comment by vitaly-t** [comment]
yep, that look ok ;)

**Pull request merged**
